[versions]
googleApi = "2.8.1"
googleAuthBom = "1.42.1"
googleSheetsApi = "v4-rev20250616-2.0.0"
hamcrest = "3.0"
j2html = "1.6.0"
quarkusPlatformVersion = "3.31.2"
quarkusPluginVersion = "3.31.2"
quarkusS3Version = "3.2.0"


[libraries]
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApi" }
google-api-sheets = { module = "com.google.apis:google-api-services-sheets", version.ref = "googleSheetsApi" }
google-auth-bom = { module = "com.google.auth:google-auth-library-bom", version.ref = "googleAuthBom" }
google-auth-library = { module = "com.google.auth:google-auth-library-oauth2-http" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
j2html = { module = "com.j2html:j2html", version.ref = "j2html" }
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkusPlatformVersion" }
quarkus-s3 = { module =  "io.quarkiverse.amazonservices:quarkus-amazon-services-bom", version.ref="quarkusS3Version"}

[plugins]
quarkus = { id = "io.quarkus", version.ref="quarkusPluginVersion" }
